### ISSUE TITLE
semaphore commit breaks build

### ISSUE THREAD

**Issue by neomantra** [nanomsg/nanomsg#53]
Commit 250bpm/nanomsg@a39847d2e5ac643b72482c3744d9f93f2a740abe breaks the build on Ubuntu 12.04

```
~/projects/nanomsg/build$ make
[  0%] Building C object src/CMakeFiles/nanomsg.dir/core/ctx.c.o
In file included from /home/evan/projects/nanomsg/src/core/ctx.c:25:0:
/home/evan/projects/nanomsg/src/core/../protocol.h:140:19: error: field ‘termsem’ has incomplete type
make[2]: *** [src/CMakeFiles/nanomsg.dir/core/ctx.c.o] Error 1
make[1]: *** [src/CMakeFiles/nanomsg.dir/all] Error 2
make: *** [all] Error 2
```

cmake had reported this:

```
-- Looking for sem_wait
-- Looking for sem_wait - not found.
```
